dtekluva/wyre-dashboard

- src/Context.js
- src/helpers/deviceDataHelper.js
- src/helpers/organizationDataHelpers.js
> [Bg] fix checkbox with date search

- package-lock.json
- src/Context.js
- src/components/ScheduleEmailModal.js
- src/helpers/organizationDataHelpers.js
- fix schedule checkbox not persistent
- fix build issues
> bug(checkbox) fix schedule checkbos

- src/components/AppHeader.js
- src/helpers/constants.js
hide score card for sapio sapio
hide time of use from all
hide messages from all
> chore(hide): hide score card for sapio

- src/components/AppHeader.js
> chore(cost-tracker): remove cost tracker for sapio

- src/Context.js
- src/components/SidebarOrganization.js
- src/helpers/genericHelpers.js
- src/mainAppPages/Dashboard.js
- handle sidebar changes
- add new context to manage all devices
- handle api call with sidebar checkbox
> bug(side checkbox) fix amount card dynamic with sidebar checkbox

- src/components/pieCharts/ScoreCardDoughnutChart.js
- src/css/style.css
- src/helpers/constants.js
- src/helpers/genericHelpers.js
- src/icons/InformationIcon.js
- src/mainAppPages/ScoreCard.js
- src/services/devices.js
- src/smallComponents/DashBoardAmountUsed.js
> [Bug] fix score card page

- src/Context.js
- src/helpers/genericHelpers.js
- src/services/devices.js
> Fix Response endpoint

- src/services/devices.js
It fixes the mock reference error
> [Bug] remove failing path reference

- src/App.js
- src/components/ScheduleEmailModal.js
- src/components/barCharts/ScoreCardBarChart.js
- src/components/pieCharts/ScoreCardFuelConsumptionDoughnut.js
- src/components/pieCharts/ScoreCardGenEfficiencyDoughnut.js
- src/helpers/constants.js
- src/helpers/genericHelpers.js
- src/mainAppPages/ScoreCard.js
- src/pageSwitchers/MainAppPages.js
- src/scss/mainAppComponents/_score-card.scss
- src/services/devices.js
- fix loading issue on scorecard
- fix schedule loading
> Fix score card page

- src/components/pieCharts/DashboardDoughnutChart.js
- src/helpers/genericHelpers.js
- src/mainAppPages/Dashboard.js
- src/mainAppPages/ScoreCard.js
- src/services/devices.js
- fix page not loading
- fix the dashboard chart to be white
> bug(dashboard): fix dashboard chart

- src/components/barCharts/ScoreCardBarChart.js
- src/components/pieCharts/ScoreCardFuelConsumptionDoughnut.js
- src/helpers/constants.js
- src/mainAppPages/ScoreCard.js
Chore/remodel fule efficiency card
> Change the piechart setting of fuel efficiency

- src/mainAppPages/EnergyConsumption.js
- src/mainAppPages/PowerDemand.js
- src/pageSwitchers/MainAppPages.js
- allow reload on parameters table
> bug(reload): fix reload page

- css/style.css
- src/css/custom-antd.css
- src/css/style.css
- src/scss/abstracts/_variables.scss
- src/scss/mainAppComponents/_billing.scss
- src/scss/mainAppComponents/_cost-tracker.scss
- src/scss/mainAppComponents/_dashboard.scss
- src/scss/mainAppComponents/_header.scss
- src/scss/mainAppComponents/_last-reading.scss
- src/scss/mainAppComponents/_main.scss
- src/scss/mainAppComponents/_parameters.scss
- src/scss/mainAppComponents/_power-quality.scss
- src/scss/mainAppComponents/_score-card.scss
- src/scss/mainAppComponents/_sidebar.scss
- src/scss/mainAppComponents/_small-components.scss
- src/scss/style.css
round up the edges of the cards
> Round up the edges of the cards

- css/style.css
- src/components/AppHeader.js
- src/css/style.css
- src/mainAppPages/ScoreCard.js
- src/scss/style.css
> hide operating time

- src/components/AppHeader.js
- src/components/NewAppTopBar.js
- src/components/barCharts/DashboardStackedBarChart.js
- src/components/barCharts/LoadOverviewPercentBarChart.js
- src/components/barCharts/RunningTime.js
- src/helpers/constants.js
- src/helpers/genericHelpers.js
- src/mainAppPages/Dashboard.js
- src/mainAppPages/LoadOverview.js
- src/scss/mainAppComponents/_load-overview.scss
> chore(load-overview): load overview on dashboard

- src/authPages/Login.js
- src/components/NewAppTopBar.js
- src/components/pieCharts/LoadConsumptionPieChart.js
- src/mainAppPages/Dashboard.js
load overview dashboard card fixes
> bug(load-overview) fix load overview dashboard information

- src/components/FormFields/CostTrackerFields.js
> chore(cost tracker) complete cost tracker

- css/style.css
- src/components/barCharts/ReportDailyConsumptionBar.js
- src/components/tables/reportTables/LoadImbalanceReportTable.js
- src/css/style.css
- src/helpers/tableColumns.js
- src/mainAppPages/Report.js
- src/scss/mainAppComponents/_report.scss
- src/smallComponents/reports/LargeDoubleCard.js
- src/smallComponents/reports/MiniDoubleCard.js
- src/smallComponents/reports/ReportWithRate.js
> fix report pages

- css/style.css
- src/Context.js
- src/components/AppHeader.js
- src/components/Sidebar.js
- src/css/style.css
- src/helpers/branchDataHelpers.js
- src/helpers/genericHelpers.js
- src/helpers/organizationDataHelpers.js
- src/mainAppPages/Dashboard.js
- src/mainAppPages/LoadOverview.js
- src/mainAppPages/ScoreCard.js
- src/pageSwitchers/MainAppPages.js
- src/scss/mainAppComponents/_header.scss
- src/scss/mainAppComponents/_sidebar.scss
- src/scss/style.css
Fix dashboard and issues on page
> Fix dashboard and issues on page

- src/mainAppPages/Dashboard.js
load overview for only bespoke
> load overview for only bespoke

- src/components/tables/reportTables/GenericReportTable.js
- src/components/tables/reportTables/ReportTimeOfUse.js
- src/components/tables/reportTables/TablesSummaries.js
- src/helpers/genericHelpers.js
- src/helpers/tableColumns.js
- src/mainAppPages/Report.js
- src/scss/mainAppComponents/_report.scss
> git add summries to some report tables

- src/components/AdminHeader.js
- src/helpers/deviceDataHelper.js
- src/helpers/genericHelpers.js
- src/helpers/organizationDataHelpers.js
- src/mainAppPages/Dashboard.js
- src/redux/reducers/index.js
> fix minimun demand

- src/mainAppPages/Dashboard.js
> add load balance to bespoke

- src/components/barCharts/DashboardStackedBarChart.js
- src/helpers/organizationDataHelpers.js
- src/helpers/renderedDataHelpers.js
- src/mainAppPages/Dashboard.js
Fix Grace court chart not showing
> fix grace court found bug

- src/components/RevisedAppTopBar.js
Buttons now showing on Dashboard
> buutons on dashboard

- src/components/AppTopBar.js
- src/components/SidebarDevice.js
- src/helpers/exportToFile.js
- src/helpers/organizationDataHelpers.js
- src/helpers/renderedDataHelpers.js
- src/helpers/tableColumns.js
- src/mainAppPages/Dashboard.js
- src/mainAppPages/Report.js
- src/redux/actions/constTracker/costTracker.action.js
- src/redux/actions/dashboard/dashboard.action.js
- src/redux/actions/powerFactor/powerFactor.action.js
- src/services/devices.js
> refactore code

- src/components/BreadCrumb.js
- src/components/SidebarDevice.js
- src/helpers/tableColumns.js
- src/mainAppPages/Report.js
> fix bread chrome issues

- src/mainAppPages/AddDieselEntry.js
- src/mainAppPages/UpdateDieselEntry.js
- src/redux/actions/constTracker/costTracker.action.js
Please don't worry about the console-logs and the comments-out, I will eradicate them when am done, please.
> Add-diesel-entry reviewed
